import type { Job } from "./types"

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Frontend Developer",
    company: "TechCorp",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$80,000 - $120,000",
    description:
      "We are looking for a talented Frontend Developer to join our team. You will be responsible for building user-facing features and ensuring great user experience.",
    requirements: ["React.js", "TypeScript", "CSS/SCSS", "3+ years experience"],
    benefits: ["Health Insurance", "Remote Work", "401k", "Flexible Hours"],
    postedDate: "2024-01-15",
    applicationDeadline: "2024-02-15",
    companyLogo: "/placeholder.svg?height=60&width=60",
    remote: true,
    experience: "Mid Level",
    category: "Engineering",
  },
  {
    id: "2",
    title: "Marketing Intern",
    company: "StartupXYZ",
    location: "New York, NY",
    type: "Internship",
    salary: "$15 - $20/hour",
    description:
      "Join our marketing team as an intern and gain hands-on experience in digital marketing, content creation, and campaign management.",
    requirements: ["Marketing knowledge", "Social Media", "Content Creation", "Student or Recent Graduate"],
    benefits: ["Mentorship", "Learning Opportunities", "Networking", "Certificate"],
    postedDate: "2024-01-10",
    applicationDeadline: "2024-02-10",
    companyLogo: "/placeholder.svg?height=60&width=60",
    remote: false,
    experience: "Entry Level",
    category: "Marketing",
  },
  {
    id: "3",
    title: "Senior Backend Engineer",
    company: "DataFlow Inc",
    location: "Austin, TX",
    type: "Full-time",
    salary: "$120,000 - $160,000",
    description:
      "Lead backend development initiatives and architect scalable systems. Work with cutting-edge technologies and mentor junior developers.",
    requirements: ["Node.js", "Python", "AWS", "Database Design", "5+ years experience"],
    benefits: ["Stock Options", "Health Insurance", "Remote Work", "Professional Development"],
    postedDate: "2024-01-12",
    applicationDeadline: "2024-02-20",
    companyLogo: "/placeholder.svg?height=60&width=60",
    remote: true,
    experience: "Senior Level",
    category: "Engineering",
  },
  {
    id: "4",
    title: "UX Designer",
    company: "DesignStudio",
    location: "Los Angeles, CA",
    type: "Contract",
    salary: "$60 - $80/hour",
    description:
      "Create intuitive and beautiful user experiences for our clients. Work on diverse projects across different industries.",
    requirements: ["Figma", "User Research", "Prototyping", "Portfolio Required"],
    benefits: ["Flexible Schedule", "Creative Freedom", "Diverse Projects"],
    postedDate: "2024-01-08",
    applicationDeadline: "2024-02-08",
    companyLogo: "/placeholder.svg?height=60&width=60",
    remote: true,
    experience: "Mid Level",
    category: "Design",
  },
  {
    id: "5",
    title: "Data Science Intern",
    company: "AI Solutions",
    location: "Seattle, WA",
    type: "Internship",
    salary: "$20 - $25/hour",
    description:
      "Work with our data science team to analyze large datasets and build machine learning models. Perfect for students looking to gain real-world experience.",
    requirements: ["Python", "Statistics", "Machine Learning", "SQL", "Student Status"],
    benefits: ["Mentorship", "Real Projects", "Learning Budget", "Full-time Opportunity"],
    postedDate: "2024-01-14",
    applicationDeadline: "2024-02-25",
    companyLogo: "/placeholder.svg?height=60&width=60",
    remote: false,
    experience: "Entry Level",
    category: "Data Science",
  },
  {
    id: "6",
    title: "Product Manager",
    company: "InnovateTech",
    location: "Boston, MA",
    type: "Full-time",
    salary: "$100,000 - $140,000",
    description:
      "Drive product strategy and work cross-functionally to deliver exceptional products. Lead product roadmap and collaborate with engineering and design teams.",
    requirements: ["Product Management", "Agile", "Analytics", "Leadership", "3+ years experience"],
    benefits: ["Equity", "Health Insurance", "Unlimited PTO", "Learning Budget"],
    postedDate: "2024-01-11",
    applicationDeadline: "2024-02-18",
    companyLogo: "/placeholder.svg?height=60&width=60",
    remote: true,
    experience: "Mid Level",
    category: "Product",
  },
]

export const jobCategories = [
  "Engineering",
  "Design",
  "Marketing",
  "Sales",
  "Product",
  "Data Science",
  "Operations",
  "Finance",
  "HR",
  "Customer Success",
]

export const locations = [
  "San Francisco, CA",
  "New York, NY",
  "Austin, TX",
  "Los Angeles, CA",
  "Seattle, WA",
  "Boston, MA",
  "Chicago, IL",
  "Denver, CO",
  "Remote",
]
